[package]
name = "groclog-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
chrono = "0.4.42"
grocery-to-json = "0.0.3"
serde = "1.0.228"
serde_json = "1.0.148"
tokio = { version = "1.48.0", features = ["rt-multi-thread"] }
tower-http = "0.6.8"
uuid = "1.19.0"
